## 例外のスロー
ここでは、例外のスローについて説明していきます。

### 目次
* [例外のスローとは](#sec1)
* [例外のスローの使用例](#sec2)

### <a name="sec1"></a>例外のスロー
例外を明示的に例外オブジェクトを作成し、意図的に例外を起こし、例外処理を実行する場合に使われます。
構文は以下になります。

```sh
throw new <例外クラス>();
```

### <a name="sec2"></a>例外のスローの使用例
以下はthrowを使用したサンプルプログラムになります。

```java
public class Sample6_4 {
	public static void main(String[] args) {
		double x = 15.0;
		double y = 0.0;
		try {
			Sample6_4 obj = new Sample6_4();
			double z = obj.doubleDivide(x, y);
			System.out.println("x / y:" + z);
		} catch (ArithmeticException ae) {
			System.out.println("An exception occurred.");
			System.out.println(ae);
		}
		System.out.println("x - y:" + (x - y));
	}
	
	double doubleDivide(double x, double y) {
		if (y == 0.0) {
			throw new ArithmeticException (
				"Integer or not, please do not divide by zero!");
		} else {
			return x / y;
		}
	}
}
```